### ISSUE TITLE
no compatible source was found for this video while running in apex 5.0

### ISSUE THREAD

**Issue by maahjoor** [Dani3lSun/apex-plugin-videoplayer#1]

**Comment by Dani3lSun** [comment]
Hi @maahjoor 
please add some more detailed description not only a subject...With this info I can´t really say what the problem can be...
Which video formats do you use? Are the links correct? And so on...

**Comment by maahjoor** [comment]
hi, 
sorry dear for this is my first time using git so i think i just submit the subject, not the details..
actually i have open an oracle thread for this as well. you could visit for the complete detail below

https://community.oracle.com/thread/3969540

Please let me know if you could help me fix it.

one more thing.. if there is any update in the Js itself, i mean from where you pick up this facility, how i could upgrade?

Regards.

**Comment by Dani3lSun** [comment]
Hi @maahjoor 
Ok you can´t use local client paths like you did...
What you need to do is to place the video files on you web server, if you use ORDS you can place the files directly under the apex image directory in a separate folder, then you can access them for example like so:
#IMAGE_PREFIX#videos/myvideo.mp4

Hope this helps!

**Comment by maahjoor** [comment]
Thank you Dani,
still the result is the same. i put the video and image under c:\app\apex\images\Videos
and reference them as #IMAGE_PREFIX#Videos/myvideo.mp4 but not working. i have remove apex from oracle 12c and install apex 5 on the above location, thats why i put it like above.

i issue the same query in apex sql command page and it give me the following resutl

![screenshot 2016-09-14 11 24 14](https://cloud.githubusercontent.com/assets/16849793/18503398/d347a150-7a6d-11e6-8571-974dc7f57395.png)

could you please guide more?

Thank you

**Comment by Dani3lSun** [comment]
Hi @maahjoor 

you can always open up the browser console to see what happens, in your case the console should say something like "resource not found (404)"...Please test a query like this one:
```
SELECT :image_prefix || 'Videos/myvideo.mp4' AS video_url,
       :image_prefix || 'danielh/videos/oceans.png' AS poster_url,
       'video/mp4' AS mime_type,
       :image_prefix || 'Videos/myvideo.webm' AS alt_video_url,
       'video/webm' AS alt_mime_type
  FROM dual
```
Important is: If you decide to use the alternative url and mime type, you should ensure that you have for example a webm file in place...In your screenshot you use both times (video url & alternative url) the same video file but different mime types...

Best wishes
Daniel
