### ISSUE TITLE
Media could not be loaded

### ISSUE THREAD

**Issue by Uditn** [Dani3lSun/apex-plugin-videoplayer#2]
Hi!

I am getting below issue when I tried to use the plugin
![image](https://cloud.githubusercontent.com/assets/25974361/25737647/95e6085c-3196-11e7-87b6-ab9bd70e8c5e.png)

Below is the query which I have used. Please suggest

select 
     'C:\Users\uditn\Desktop\TEST.mp4' AS video_url,
    'C:\Users\uditn\Desktop\Photo.jpg' AS poster_url ,
'video/mp4' AS mime_type
  from DUAL

**Comment by Dani3lSun** [comment]
Hi @Uditn 
you can´t select the real Path from your filesystem, you have to specific the path from webservers view, e.g:
#IMAGE_PREFIX#videos/TEST.mp4
So you have to upload the videos to your webserver.

**Comment by Uditn** [comment]
Hey!

Thanks for the prompt reply. 
I am saving the video URL,POSTER URL,MIME_TYPE in a table and want to display the video from that table only. Still I need to upload the video on web servers? Please suggest.

**Comment by Dani3lSun** [comment]
Then I would suggest you to create a download blob procedure and do it via an AJAX Application Process. The URL is then a link to the application process with a file-id or something like that...
Carsten Czarski wrote a nice download article about that in german, maybe you can use Google Translate:
https://apex.oracle.com/pls/apex/germancommunities/apexcommunity/tipp/4221/index.html

**Comment by Uditn** [comment]
I am able to download the video. But I now want make a video gallery. The link you mentioned is for downloading the file. How can I make a video gallery in apex in which videos are coming from a table.
Please suggest.
https://community.oracle.com/thread/4042971

Best Regards

**Comment by Dani3lSun** [comment]
You know that a browser downloads a video when displaying it, so you first need a download procedure, the link to that procedure is than used in the plugin sql query...

```
SELECT apex_util.prepare_url('f?p=' || :app_id || ':1:' || :app_session ||
                             ':APPLICATION_PROCESS=DOWNLOAD_FILE&X01=' ||
                             file_id) AS video_url,
       apex_util.prepare_url('f?p=' || :app_id || ':1:' || :app_session ||
                             ':APPLICATION_PROCESS=DOWNLOAD_FILE&X01=' ||
                             file_id_2) AS poster_url,
       mime_type
  FROM file_table
```
This means that you have to create an Application Process which downloads a file first...

**Comment by Uditn** [comment]
Hey,
I am unable to understand how to implement it as I am novice to Oracle apex. So will you please elaborate? 

Best Regards.
