### ISSUE TITLE
Blob Source

### ISSUE THREAD

**Issue by jeanmarc78** [Dani3lSun/apex-plugin-videoplayer#3]
hello,
is there a way to make the plugin work with a blob source table ?

regards
jm

**Comment by Dani3lSun** [comment]
Hi @jeanmarc78 

you can achieve this by creating a download application process. I already mentioned this way in this issue:
https://github.com/Dani3lSun/apex-plugin-videoplayer/issues/2#issuecomment-299421008

**Comment by jeanmarc78** [comment]
hello Dani
thanks
best regards
jm
